/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          colors: {
              "tertiary-container": "#1bbd85",
              "outline": "#869397",
              "inverse-surface": "#dae2fd",
              "inverse-on-surface": "#283044",
              "on-background": "#dae2fd",
              "surface-dim": "#0b1326",
              "primary-container": "#06b6d4",
              "surface-tint": "#4cd7f6",
              "on-tertiary-container": "#00452e",
              "on-primary-fixed-variant": "#004e5c",
              "on-primary-fixed": "#001f26",
              "on-secondary-container": "#d6a9ff",
              "on-secondary-fixed-variant": "#6900b3",
              "primary-fixed": "#acedff",
              "on-tertiary": "#003824",
              "on-tertiary-fixed-variant": "#005236",
              "secondary": "#ddb7ff",
              "on-secondary-fixed": "#2c0051",
              "on-secondary": "#490080",
              "tertiary-fixed": "#6ffbbe",
              "on-error": "#690005",
              "on-surface-variant": "#bcc9cd",
              "on-primary": "#003640",
              "outline-variant": "#3d494c",
              "surface-variant": "#2d3449",
              "primary-fixed-dim": "#4cd7f6",
              "primary": "#4cd7f6",
              "on-surface": "#dae2fd",
              "on-error-container": "#ffdad6",
              "tertiary-fixed-dim": "#4edea3",
              "surface-container-highest": "#2d3449",
              "tertiary": "#4edea3",
              "surface-container-low": "#131b2e",
              "surface": "#0b1326",
              "surface-container": "#171f33",
              "surface-container-lowest": "#060e20",
              "secondary-fixed-dim": "#ddb7ff",
              "on-primary-container": "#00424f",
              "surface-container-high": "#222a3d",
              "error": "#ffb4ab",
              "surface-bright": "#31394d",
              "background": "#0b1326",
              "secondary-container": "#6f00be",
              "secondary-fixed": "#f0dbff",
              "on-tertiary-fixed": "#002113",
              "inverse-primary": "#00687a",
              "error-container": "#93000a"
          },
          fontFamily: {
              "headline": ["Space Grotesk", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"]
          },
      },
  },
  plugins: [],
}
